server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
